{% set version = "1.0" %}

package:
  name: pyomo.solvers
  version: {{ version }}

build:
  number: 1001

requirements:
  host:
    - python
  run:
    - python
    - ipopt
    - glpk
    - coincbc  # [unix]

test:
  commands:
    - test -f $PREFIX/bin/ipopt  # [unix]
    - test -f $PREFIX/bin/glpsol  # [unix]
    - test -f $PREFIX/bin/cbc  # [unix]
    - if not exist %LIBRARY_BIN%\\ipopt.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\glpsol.exe exit 1  # [win]

about:
  home: http://pyomo.org
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: 'Optimizers that enhance the functionality of Pyomo'

extra:
  recipe-maintainers:
    - whart222
    - jsiirola
