travis:
  secure:
    BINSTAR_TOKEN: CJpPjmyV1vWBpi+niHOtpE23X8fTW0aMX+VwLUOTp228EjaRPVlt3hbReTEIz3UVco0fSljVKwnJUW5asawJ81zts2YHtW7oKR219YYnG2kDof2sfDxejKCYTFnGs347CaVZXTe7ZnrbLw3OqnCsECb5f3/t+NTSZiJYcP/wf2toHlh+YObSoXnbzxv8FEsnOtOKLa1hjw73061NASRmAqVSqJqPbKMWN0NPk5rUNh9M25+8vKoGQqk/VDSjgn+TgVNqweJV4n0d0kD98CNjUvbedwlcDKqSR3CfA5vnRbRxKiBP9zI8UAwvtvHUkfM5LBzyxnJtmYy9Iw1MH1t+u+rk80QNBTlXt6c/0A1TkreLlP+STQS/uCPEjICK0bpfUZiAwthpXpsCd4WD6artkDxO6LXir16lcfc/aYA4wRudETfzUua0FPMNJbiUn2d5rfzccNsf+eq8RykhuoEb93lTMcQFzq4v82nC7GfTdyzKxLGfDSsRERN8ldKIIU9ARAQZHV3LP3WTyDH1cMINIMsGQ0ggx+Wupddue8UjFZNIKU0HsS31IbuGUvm34t4XoXYqmXvoGbE925g06RY6auWgW2qwc7D8V4iBn/s7uuGceJtti64gLeNkO54VuAtOdics0bbv4cUxd66osLXmPU1oJvIiZK8rFmXOVLMtuos=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
