travis:
  secure:
    BINSTAR_TOKEN: d/WWrKHjiWJEKnOBzsAwyjFwrdHKmz2WgBdIBfGNSPHDOsjSRaAg9pSiwkcqdxr9rUAizohv+jU5dMrzzj6v4H9un4OeT1L8Y6bTXWGdtMEHzKC4bcusXHslX3JcwpQKPX+yhuUA1vMPZFlRrhtB9rdcEfTcH2KqI20iCYbHf1ORldeRqonBtG+8s0BYMcDfDXwxFJZl7PAbV2KjFuLkkPPRsGXV9PAANfsfQAhUtrkQQzACNOvCdLAnNOgH2QFsJ5G/K74uza4LXbI3l0XQi6Px0PQiVa/elI2B2YbIjt5i2Em6UBN0yJPxDr1jGBsYMdOhLgbfPYmlmTqjQ7eEUswvNcFkzXgr4EpbRPFoZN340qr4P1Bk8oS0WMmZSlSbxsatxdyMLUYkUS31XzgU3yOZ4Jddu5/1/D+TQ445ztK4oy2WphHIXrWnHgM05WJgYE5U8IviF3BHs0dhz6pesYEdu4i7LM5UUArHnlXaW4dWAEO9mXloOKHUPZTn1oBgHiZ7Z/ovwMN+J8D1vuOcrINwKnZbCLzNPs7UpyJHrnE8uH0vKvmkikhsdNN+gTKsSpTGrfAc9scQ3sLfNLGunawOmxJXWcCg/6o96w5D84eOG938s8MeBR7qyHWXaslA9oxWLnzG+HRxL6JiMQD0PX90IrUKk579iEz5XOjcHIY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
